name: Code Analize

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          TARGET: windows
        sdk: [stable]

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: ${{matrix.sdk}}

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Doctor
        run: flutter doctor -v

      - name: Enable desktop support
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Build Release
        run: |
          flutter build -v ${{matrix.TARGET}} --release

      - name: Create a Zip Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'RobotLauncher-${{matrix.TARGET}}.zip'
          directory: './build/${{matrix.TARGET}}/runner/release'
          exclusions: '*.lib *.exp'

      - run: ls
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: release-${{ matrix.os }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./build/windows/runner/release/RobotLauncher-${{matrix.TARGET}}.zip